name: FOV Linux CI & Analysis

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_program_compilation_linux:
    name: FOV - Build on Linux
    runs-on: [ self-hosted, linux, x64, ubuntu ]
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build (Debug)
        run: ./.github/scripts/FOV/build_linux.sh

      - name: Upload Full Build Directory for Analyzer
        uses: actions/upload-artifact@v7
        with:
          name: linux-build-folder
          path: build/
          retention-days: 1

      - name: Upload Linux Artifact (Debug)
        uses: actions/upload-artifact@v7
        with:
          name: FOV-linux-x64-debug
          path: build/rundir/

  cppcheck:
    name: Code analyzer cppcheck
    needs: check_program_compilation_linux
    runs-on: [ self-hosted, linux, x64, ubuntu ]
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Download Linux Build Folder
        uses: actions/download-artifact@v7
        with:
          name: linux-build-folder
          path: build/

      - name: Run cppcheck
        run: ./.github/scripts/FOV/run_cppcheck.sh

      - name: Publish cppcheck
        if: always()
        run: ./.github/scripts/FOV/cppcheck_publisher.sh

      - name: Upload cppcheck artifact
        uses: actions/upload-artifact@v7
        with:
          name: cppcheck
          path: check.txt

  codechecker-scan:
    name: CodeChecker C++ Scan
    runs-on: [ self-hosted, linux, x64, ubuntu ]
    needs: check_program_compilation_linux
    timeout-minutes: 60
    if: >-
      (github.event_name == 'push' && (github.ref_name == 'dev' || github.ref_name == 'master')) ||
      (github.event_name == 'pull_request' && (github.base_ref == 'dev' || github.base_ref == 'master'))
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Download Linux Build Folder
        uses: actions/download-artifact@v7
        with:
          name: linux-build-folder
          path: build/

      - name: Run CodeChecker Analysis
        run: |
          CodeChecker analyze ./build/compile_commands.json --output ./reports

      - name: Export to SARIF
        if: always()
        run: |
          CodeChecker parse ./reports --export sarif --output results.sarif || true

      - name: Upload results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: results.sarif
          category: codechecker

